# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Democracy Now
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Développer ensemble des solutions open source* pour la démocratie.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://opendemocracynow.net/" # the base hostname & protocol for your site
twitter_username: ODN
github_username:  opendemocracynow
gems: [jekyll-paginate]
paginate: 6
paginate_path: "/projets/page:num/"

collections:
 hackathons:
  output: true
  permalink: /hackathons/:title

# Build settings
markdown: kramdown
permalink: /:categories/:title

github:
  repo: opendemocracynow/opendemocracynow.github.io
  branch: master
